"""The landing page is a second copy of facts that live in the code.

This repo has shipped three READMEs pointing at renamed URLs, so a second
surface only earns its place if something checks it. These tests are that
something, and CI runs them.
"""

import asyncio
import re
from pathlib import Path

import pytest

from gopher.config import DIGEST_BUDGET
from gopher.server import mcp

PAGE = Path(__file__).resolve().parents[1] / "docs" / "index.html"


@pytest.fixture(scope="module")
def page() -> str:
    return PAGE.read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def served_tools() -> set[str]:
    return {t.name for t in asyncio.run(mcp.list_tools())}


def _documented_tools(page: str) -> set[str]:
    """Tool names from the reference table, as `name(args)` in a code tag."""
    rows = re.findall(r"<td><code>([a-z_]+)\(", page)
    return set(rows)


def test_the_page_exists():
    assert PAGE.exists(), "docs/index.html is what GitHub Pages serves"


def test_every_served_tool_is_documented(page, served_tools):
    missing = served_tools - _documented_tools(page)
    assert not missing, f"tools the server exposes but the page does not list: {sorted(missing)}"


def test_the_page_documents_no_tool_that_does_not_exist(page, served_tools):
    invented = _documented_tools(page) - served_tools
    assert not invented, f"tools the page lists but the server does not expose: {sorted(invented)}"


def test_the_tool_count_in_the_heading_is_right(page, served_tools):
    """The heading says a number out loud, so it can be wrong out loud."""
    words = {
        9: "Nine",
        10: "Ten",
        11: "Eleven",
        12: "Twelve",
        13: "Thirteen",
        14: "Fourteen",
    }
    expected = words.get(len(served_tools))
    assert expected, f"add {len(served_tools)} to this mapping"
    assert f"{expected} tools" in page


def test_the_documented_budget_matches_the_code(page):
    assert f"{DIGEST_BUDGET}" in page, f"page should state the real default budget, {DIGEST_BUDGET}"


def test_env_vars_on_the_page_all_exist(page):
    """Catches a variable renamed in config.py and left stale on the page."""
    from gopher import config

    documented = set(re.findall(r"<code>(GOPHER_[A-Z_]+)</code>", page))
    assert documented, "no environment variables found on the page"
    for name in documented:
        assert hasattr(config, name.removeprefix("GOPHER_")) or name in Path(
            config.__file__
        ).read_text(encoding="utf-8"), f"{name} is documented but not read anywhere in config.py"


def test_the_page_needs_no_javascript_to_read(page):
    """Scripts are allowed as enhancement, never as a requirement."""
    body = page.split("<body>", 1)[1]
    for block in re.findall(r"<script[^>]*>(.*?)</script>", body, re.S):
        assert "document.write" not in block, (
            "content generated by script is not readable without it"
        )
    assert "<noscript" not in page or "required" not in page.lower()


#: Hosts the page is allowed to mention at all. Kept as an allowlist rather
#: than a scan for known CDNs, because the next font host will not be on any
#: list of known font hosts.
ALLOWED_HOSTS = ("https://github.com/", "https://ollama.com")


def test_the_page_loads_no_third_party_assets(page):
    """No fonts, no CDNs, no analytics. Outbound links are fine.

    Matches every URL anywhere on the page rather than quoted src and href
    only. An unquoted attribute is still valid HTML and still a request,
    and an earlier version of this test let one straight through.
    """
    for url in re.findall(r"https?://[^\s\"'<>)]+", page):
        assert url.startswith(ALLOWED_HOSTS), (
            f"{url} is not an allowed host. If the page needs it, add it to "
            "ALLOWED_HOSTS deliberately."
        )
